### ISSUE TITLE
PWM does not update fast enough causing flicker

### ISSUE THREAD

**Issue by dragan1alex** [bigjosh/ShiftPWM-Redux#1]
I have set the refresh rate from 30 up to 240 with flickering when setting any pwm value from 1 to 254. Can it be because attiny85/45/25 can run on the PLL clock, so timer0 might not be running at 1khz?
The attiny I'm using is clocked at 16MHz (boards manager json: https://raw.githubusercontent.com/damellis/attiny/ide-1.6.x-boards-manager/package_damellis_attiny_index.json).

If you can look into this issue I'd be very grateful :)

**Comment by bigjosh** [comment]
There are lots of different clock sources that an ATTINY can be configured to use, and then different prescalers for each clock source. I'd start from a known configuration and then verify the clock is running at the speed you think it is - maybe my manually outputting a square wave using the Timer. Once you _know_ the clock speed it right, then you can start digging deeper if you still have problems.

**Comment by dragan1alex** [comment]
What board (bootloader) did you use to test the library on? I'm using the above mentioned one (attiny85, 16MHz internal clock) with no success by far.
I've reconfigured the library to use the timer1 for interrupts (since I can screw with it without messing the timing functions), set it to trigger an interrupt at 1khz-ish without any visible result.
The code I've added to CShiftPWM.h:

```
PLLCSR |= 1<<PLLE; //enable PLL
delay(1); //wait for PLL to stabilize, it needs about 100microseconds to stabilize
PLLCSR |= 1<<PLOCK | 1<<PCKE; //set PLL as clock source for timer1
TCCR1 |= 1<<CTC1 | 1<<CS10 | 1<<CS13; //set timer1 in CTC mode, prescale 256
OCR1A = 124;
/*
From Atmels datasheet, the frequency is calculated using the formula fq = clock/(2*prescale*(1+OCR1A))
Since the clock is 64MHz, 1+OCR1A = 64000000/(fq*2*prescale)
*/
TIMSK |= 1<<OCIE1A;
sei();
```

also the line
`m_irqPrescaler = (ledFrequency / 1000)+1;`
doesn't make any sense to me, m_irqPrescaler is declared as uint8_t so basically it will always will have the value 1?

Sorry for being a noob, I'm kind of new to programming microcontrollers and I'm trying to learn how all of this works , can you please explain me what I'm doing wrong?

**Comment by bigjosh** [comment]
> What board (bootloader) did you use to test the library on? I'm using the above mentioned one (attiny85, 16MHz internal clock) with no success by far.

Do you have a standard Arduino UNO(-ish?) board you can use to test your setup with the example code? This would prove out that there no problems with the shift registers or other hardware assumptions. 

Once you have that working we can take small individual steps forward (i.e switch from UNO to your board, change Timer, change clock) to get to your final working configuration. It is very hard to start with something that has lots of changes and is not working since there are so many potential places to look. 

> also the line
> m_irqPrescaler = (ledFrequency / 1000)+1;
> doesn't make any sense to me, m_irqPrescaler is declared as uint8_t so basically it will always will have the value 1?

If `ledFreqency` is less than 2000, then the `irqPrescaler` will be 1. When set to `1`, then the LEDs will update on every interrupt, which is 1KHz. By calling `Start()`, with an `ledFreqency` of, say, 2000 then the update rate would only be 500Hz. Absolutely agree that `ledFreqency` is a misleading name and range for this parameter, maybe at some point this made sense but not now. ! `Start` should probably take the prescaler directly as an `unsigned char`.

**Comment by dragan1alex** [comment]
I have tested this library on an arduino uno r3 and it still flickers, pointing at a software problem rather than a hardware one. The original library works fine, fades the leds nicely, this one, ran with the same parameters (2 shift registers, 60hz, same pins set for data, clock, latch) is flickering. If you have some shift registers you can test if yourself, daisy chain 2 registers and wire as following: data-A0, clock-D5, latch-D4.

**Comment by bigjosh** [comment]
Ok, great starting point. Let me dig up some shift registers and see if I can reproduce! Thanks!

**Comment by jfraf** [comment]
Did you come up with a solution yet? I have the same problem as dragan1alex, meaning that smooth fading works using the original ShiftPWM library (uno r3), but the redux version only causes the LEDs to blink more or less randomly (tested on uno r3 and an attiny85, for which I intended to use ShiftPWM-Redux).

Here's my minimal example for ShiftPWM-Redux (pin layout for uno):
```
const int ShiftPWM_latchPin = 8;
const int ShiftPWM_dataPin = 11;
const int ShiftPWM_clockPin = 13;

const unsigned int ShiftPWM_numRegisters = 1;

const bool ShiftPWM_invertOutputs = false; 
const bool ShiftPWM_balanceLoad = false;

#include <ShiftPWM.h>

unsigned char maxBrightness = 255;
unsigned char pwmFrequency = 75;

void setup(){
  ShiftPWM.SetPinGrouping(1); 
  ShiftPWM.Start(pwmFrequency,maxBrightness);
}

void loop()
{    
  // Fade in all outputs
  for(int j=0;j<maxBrightness;j++){
    ShiftPWM.SetAll(j);  
    delay(3);
  }
  // Fade out all outputs
  for(int j=maxBrightness;j>=0;j--){
    ShiftPWM.SetAll(j);  
    delay(3);
  }
}
```

And a very similar one for the original ShiftPWM:
```
const int ShiftPWM_latchPin = 8;
#define SHIFTPWM_NOSPI
const int ShiftPWM_dataPin = 11;
const int ShiftPWM_clockPin = 13;

const bool ShiftPWM_invertOutputs = false; 
const bool ShiftPWM_balanceLoad = false;

#include <ShiftPWM.h>  
unsigned char maxBrightness = 255;
unsigned char pwmFrequency = 75;
int numRegisters = 1;
int numRGBleds = numRegisters*8/3;

void setup(){
  ShiftPWM.SetAmountOfRegisters(numRegisters);
  ShiftPWM.SetPinGrouping(1);
  ShiftPWM.Start(pwmFrequency,maxBrightness);
}

void loop()
{    
  // Fade in all outputs
  for(int j=0;j<maxBrightness;j++){
    ShiftPWM.SetAll(j);  
    delay(3);
  }
  // Fade out all outputs
  for(int j=maxBrightness;j>=0;j--){
    ShiftPWM.SetAll(j);  
    delay(3);
  }
}
```

It would be great if you could reproduce/fix the issue. Thanks!
