### ISSUE TITLE
timing error

### ISSUE THREAD

**Issue by BogdanTheGeek** [bigjosh/ShiftPWM-Redux#3]
Hi, I am trying to run the rgb example but it does not work properly.
Every time it tries to pwm it just flashes with the duration of the flash proportional to the assumed duty cycle.
i have the same code running on a nano but the same issue.
Can you help me out?

**Comment by bigjosh** [comment]
I will try to take a look tomorrow...

**Comment by BogdanTheGeek** [comment]
thank you!

**Comment by BogdanTheGeek** [comment]
i also seem to get problems compiling when i include softwareSerial 
/documents/arduino-1.0.6/hardware/tools/avr/bin/../lib/gcc/avr/4.3.2/../../../../avr/lib/avr25/crttn85.o:(.init9+0x2): relocation truncated to fit: R_AVR_13_PCREL against symbol `exit' defined in .fini9 section in /documents/arduino-1.0.6/hardware/tools/avr/bin/../lib/gcc/avr/4.3.2/avr25\libgcc.a(_exit.o)
could it be due to a timer conflict? how can this be resolved?

**Comment by BogdanTheGeek** [comment]
nevermind, updating the IDE fixed it :)

**Comment by BogdanTheGeek** [comment]
have you had any time to look over the library?

**Comment by bigjosh** [comment]
Please do not use this code. I am not going to be able to get this working for you. Sorry.
